# Generated by Django 4.0.1 on 2022-01-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telefone',
        ),
    ]
