# Generated by Django 4.0.1 on 2022-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0003_balance_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'CURRENT'), (2, 'SAVINGS')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'RENT'), (2, 'BILLS'), (3, 'CAR'), (4, 'TRAVEL'), (5, 'HEALTH'), (6, 'GROCERIES'), (7, 'FUN'), (8, 'CLOTHES'), (9, 'CHARITY')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'GIFT'), (4, 'OTHER')]),
        ),
    ]
