# Generated by Django 4.0.1 on 2022-01-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0008_rename_comment_text_income_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
