# Generated by Django 4.0.1 on 2022-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0010_balance_user_expense_comment_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='date',
            field=models.DateField(default='2001-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
