# Generated by Django 4.0.1 on 2022-01-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0011_balance_comment_balance_date_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Corrente'), (2, 'Poupança')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Não se aplica'), (2, 'Dias'), (3, 'Semanas'), (4, 'Meses'), (5, 'Anos')], default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Casa'), (2, 'Educação'), (3, 'Eletrônicos'), (4, 'Lazer'), (5, 'Outros'), (6, 'Transporte'), (7, 'Restaurante'), (8, 'Roupas'), (9, 'Saúde'), (10, 'Serviços'), (11, 'Supermercado'), (12, 'Viajem')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Não se aplica'), (2, 'Dias'), (3, 'Semanas'), (4, 'Meses'), (5, 'Anos')], default=1),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Bonus'), (2, 'Invesimentos'), (3, 'Outros'), (4, 'Presente'), (5, 'Salario')]),
        ),
    ]
