# Generated by Django 4.0.1 on 2022-01-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0012_alter_balance_type_alter_expense_repetition_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='repetition_interval',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='repetition_time',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='repetitive',
        ),
        migrations.RemoveField(
            model_name='income',
            name='repetition_interval',
        ),
        migrations.RemoveField(
            model_name='income',
            name='repetition_time',
        ),
        migrations.RemoveField(
            model_name='income',
            name='repetitive',
        ),
    ]
