# Generated by Django 4.0.1 on 2022-01-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_pub_future', '0013_remove_expense_repetition_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Bônus'), (2, 'Invesimentos'), (3, 'Outros'), (4, 'Presente'), (5, 'Salário')]),
        ),
    ]
